
// Random Space Facts Array
const spaceFacts = [
    "A day on Venus is longer than a year on Venus!",
    "Neutron stars can spin 600 times per second.",
    "A spoonful of a neutron star weighs about a billion tons.",
    "There are more stars in the universe than grains of sand on Earth.",
    "One million Earths could fit inside the Sun.",
    "A year on Mercury is just 88 Earth days.",
    "Space is completely silent because sound needs a medium to travel.",
    "The Sun is 93 million miles away from Earth.",
    "Jupiter's Great Red Spot is a giant storm that's been raging for over 300 years.",
    "A full NASA space suit costs around $12 million.",
    "A day on Mars is only slightly longer than a day on Earth.",
    "The footprints on the Moon will remain there for millions of years.",
    "One day on the planet Mercury lasts nearly 59 Earth days.",
    "Saturn has 82 moons, more than any other planet in our solar system.",
    "The largest volcano in the solar system is on Mars—it's called Olympus Mons.",
    "Uranus rotates on its side, making it the only planet that does.",
    "The hottest planet in our solar system is Venus, not Mercury.",
    "Mars has seasons, just like Earth.",
    "The temperature on the dark side of the Moon drops to -280°F (-173°C).",
    "The Milky Way galaxy is over 100,000 light-years wide.",
    "In space, metal sticks together without needing to be welded.",
    "Pluto is smaller than the USA.",
    "Jupiter's moon Ganymede is the largest moon in the solar system and even bigger than Mercury.",
    "Light from the Sun takes about 8 minutes to reach Earth.",
    "Saturn's rings are made of ice, dust, and rock.",
    "The coldest place in the universe is the Boomerang Nebula, at -458°F (-272°C).",
    "A day on Saturn lasts only 10 hours.",
    "The Sun is actually a white star, but appears yellow because of Earth's atmosphere.",
    "The closest galaxy to the Milky Way is the Andromeda Galaxy.",
    "It would take 225 million years for the Sun to orbit the Milky Way once.",
    "Mars has the largest dust storms in the solar system, lasting for months.",
    "Astronauts grow taller in space because their spines stretch out.",
    "There's a planet made entirely of diamonds called 55 Cancri e.",
    "The Moon is slowly drifting away from Earth by about 1.5 inches per year.",
    "The largest asteroid is Ceres, which is about 600 miles wide.",
    "The Sun accounts for 99.86% of the mass in the solar system.",
    "A neutron star can be as small as a city but contain more mass than our Sun.",
    "Mercury has no atmosphere, meaning it has extreme temperature swings.",
    "Venus spins in the opposite direction of most planets.",
    "One year on Neptune is 165 Earth years.",
    "Black holes aren't actually holes—they're incredibly dense objects with strong gravitational pulls.",
    "There's a giant cloud of alcohol in space, 1,000 times the diameter of our solar system.",
    "The International Space Station orbits Earth at 17,500 miles per hour.",
    "Saturn could float in water because it's mostly made of gas.",
    "Earth is the only planet not named after a god or goddess.",
    "Mars is home to the deepest canyon in our solar system, Valles Marineris.",
    "If two pieces of metal touch in space, they will bond together permanently.",
    "The Sun will eventually turn into a red giant, engulfing the inner planets.",
    "There are volcanoes on Mars that might still be active today.",
    "Some planets, like Jupiter, have rings, but Saturn's are the most visible."
];

module.exports = spaceFacts;
